### ISSUE TITLE
Inverted Swim Controls

### ISSUE THREAD

**Issue by toadettexmushina** [ori-community/wotw-seedgen#125]
Add toggle inverted swim speed controls to the rando wheel, instead of having to change it in the rando client and restart the game

**Comment by timoschwarzer** [comment]
Currently, Alt+L is sufficient to reload it after having changed the setting in the launcher.

**Comment by SiriusAshling** [comment]
Is there something that would make you want to toggle inverted swim speed mid seed? If so it sounds like that's an issue with the feature, it shouldn't be something you have to toggle on the fly ever.
That would be a question for the client though, closing this on seedgen side

**Comment by toadettexmushina** [comment]
It was more of an issue before the slowdown was removed, since logic expected you to go as fast as possible, but between that and Alt-L working it's not necessary.
