### ISSUE TITLE
Glades Done bugs

### ISSUE THREAD

**Issue by timoschwarzer** [ori-community/wotw-seedgen#133]
When playing with Glades Done, not all projects seem to be bought. The Moki Father is also still in front of his hut and will never die.

![image](https://github.com/ori-community/wotw-seedgen/assets/8849554/1420b1d3-e499-446a-b64a-d9c8d1cb1ac6)

**Comment by MunWolf** [comment]
Fixed the issue with the Moki and entering huts.
The project not being bought seems to be a seedgen issue because there is a line in the seed that sets that state back to 1 (after glades done sets it to 3)

**Comment by MunWolf** [comment]
[53ce361a22e32fb86a0e8379f6186197316a1d08 ](https://github.com/ori-community/wotw-rando-client/commit/53ce361a22e32fb86a0e8379f6186197316a1d08) relevant commit
