### ISSUE TITLE
Remove paths without DJ from left to center burrows

### ISSUE THREAD

**Issue by timoschwarzer** [ori-community/wotw-seedgen#85]
![image](https://user-images.githubusercontent.com/8849554/181648192-54c579ec-046c-4aa3-a1ea-718cc65b6787.png)

that slug is camping.

**Comment by MunWolf** [comment]
You can get past him pretty easily using this trick
https://user-images.githubusercontent.com/3696546/181690792-26a51404-0030-47fa-b801-77a4031b2a51.mp4
But expecting Gorlek users to know this, especially since its unneeded if the slug isn't being a dick is probably not correct?

**Comment by Foopyo** [comment]
Pathfinding part done on this commit 763964462af689ddc76fe34d464caaccd206293b .
Still need someone to validate the paths and then cherry pick it to the main branch.

**Comment by Foopyo** [comment]
Closing in favor of #107
